export interface paymentInterface {
    BRI?: number,
    BCA?: number,
    MANDIRI?: number,
    BNI?: number,
    BSI?: number,
    DANA?: number,
    GOPAY?: number,
    SHOPEEPAY?: number,
    LINKAJA?: number,
    OVO?: number,
    account_number?: number,
    bank_code?: string,
    accountHolderName?: string,
    isEnabled?: boolean,
    BRI_status?: boolean,
    BCA_status?: boolean,
    MANDIRI_status?: boolean,
    BNI_status?: boolean,
    DANA_status?: boolean,
    GOPAY_status?: boolean,
    SHOPEEPAY_status?: boolean,
    LINKAJA_status?: boolean,
    OVO_status?: boolean,
    amount?: number,
    revenue_id?: string
}